### ISSUE TITLE
Crash upon creating or loading world.

### ISSUE THREAD

**Issue by 0963Iboss222** [Fabulously-Optimized/fabulously-optimized#205]
### Describe the bug

I have the latest version of FO it launches with no problem but when I try to open a world or create one for a few seconds "saving world" appears on screen then the game crashes. Note enough crashes also isn't able to identify the cause.

Copy and pasted from the crash notepad.

<details>

```
---- Minecraft Crash Report ----
// My bad.

Time: 12/21/21, 4:48 PM
Description: Starting integrated server

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3324 failed
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.7)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.client.MinecraftClient.method_29603(MinecraftClient:2048)
	at net.minecraft.server.MinecraftServer.startServer(MinecraftServer:277)
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:2048)
	at net.minecraft.client.MinecraftClient.method_29608(MinecraftClient:2021)
	at net.minecraft.client.MinecraftClient.method_29605(MinecraftClient:2122)
	at net.minecraft.client.gui.screen.ConfirmScreen.method_37054(ConfirmScreen:56)
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:40)
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16)
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:121)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27)
	at net.minecraft.client.Mouse.method_1611(Mouse:94)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:491)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94)
	at net.minecraft.client.Mouse.method_22686(Mouse:165)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
	at net.minecraft.client.Mouse.method_22684(Mouse:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem:220)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1145)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$ckm000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:13035)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:755)
	at net.minecraft.client.main.Main.main(Main:238)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 36 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [dehydration.mixins.json:PlayerManagerMixin] from phase [DEFAULT] in config [dehydration.mixins.json] from mod [dehydration] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 39 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded NullPointerException whilst transforming the mixin class: [INJECT Applicator Phase -> dehydration.mixins.json:PlayerManagerMixin -> Apply Injections -> PreInject -> dehydration.mixins.json:PlayerManagerMixin->@Inject::respawnPlayerMixin(Lnet/minecraft/class_3222;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_2338;FZLnet/minecraft/class_3218;Ljava/util/Optional;Lnet/minecraft/class_3218;Lnet/minecraft/class_3222;)V from mod dehydration]
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.7)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1390)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 39 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_310.method_29603(class_310.java:2048)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:277)
	at net.minecraft.class_310.method_29610(class_310.java:2048)
	at net.minecraft.class_310.method_29608(class_310.java:2021)
	at net.minecraft.class_310.method_29605(class_310.java:2122)
	at net.minecraft.class_410.method_37054(class_410.java:56)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:121)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)

-- Starting integrated server --
Details:
	Level ID: New World
	Level Name: New World
Stacktrace:
	at net.minecraft.class_310.method_29610(class_310.java:2048)
	at net.minecraft.class_310.method_29608(class_310.java:2021)
	at net.minecraft.class_310.method_29605(class_310.java:2122)
	at net.minecraft.class_410.method_37054(class_410.java:56)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:121)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:220)
	at net.minecraft.class_310.method_1523(class_310.java:1145)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$ckm000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:13035)
	at net.minecraft.class_310.method_1514(class_310.java:755)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_410
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:220)
	at net.minecraft.class_310.method_1523(class_310.java:1145)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$ckm000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:13035)
	at net.minecraft.class_310.method_1514(class_310.java:755)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, lambdabettergrass/default, continuity/default, continuity/glass_pane_culling_fix, Mod Menu Helper.zip
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2409)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$ckm000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:13035)
	at net.minecraft.class_310.method_1514(class_310.java:755)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 455699136 bytes (434 MiB) / 929038336 bytes (886 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Pentium(R) CPU N4200 @ 1.10GHz
	Identifier: Intel64 Family 6 Model 92 Stepping 9
	Microarchitecture: Goldmont
	Frequency (GHz): 1.09
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 505
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5a84
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8681
	Memory slot #0 capacity (MB): 1024.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: LPDDR4
	Memory slot #1 capacity (MB): 1024.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: LPDDR4
	Memory slot #2 capacity (MB): 1024.00
	Memory slot #2 clockSpeed (GHz): 1.60
	Memory slot #2 type: LPDDR4
	Memory slot #3 capacity (MB): 1024.00
	Memory slot #3 clockSpeed (GHz): 1.60
	Memory slot #3 type: LPDDR4
	Virtual memory max (MB): 11084.85
	Virtual memory used (MB): 8269.63
	Swap memory total (MB): 7157.36
	Swap memory used (MB): 2013.73
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4
		advancementinfo: AdvancementInfo 1.18-fabric0.43.1-1.3
		amecsapi: Amecs API 1.3.2+mc1.18-pre1
		animatica: Animatica 0.1+1.17
		antighost: AntiGhost 1.18-fabric0.43.1-1.1.4
		apoli: Apoli 2.2.2
		appleskin: AppleSkin mc1.18-2.2.0
		architectury: Architectury 3.2.51
		autoconfig1u: Auto Config v1 Updated 3.2.2
		backslot: BackSlot 1.2.3
		backslotaddon: BackSlot Addon 1.0.7
		betterbeds: Better Beds 1.2.0
		bettermounthud: Better Mount HUD 1.1.3
		bettersafebed: BetterSafeBed 1.18-fabric-a
		blue_endless_jankson: jankson 1.2.1
		borderlessmining: Borderless Mining 1.1.1+1.18
		calio: Calio 1.4.2
		capes: Capes 1.2.2+1.18
		cardinal-components-base: Cardinal Components API (base) 4.0.0-alpha.1+21w37a
		cardinal-components-entity: Cardinal Components API (entities) 4.0.0-alpha.1+21w37a
		cem: Custom Entity Models 0.7.0
		chat_heads: Chat Heads 0.6.0
		citresewn: CITResewn 0.8.1-1.18
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config: Cloth Config v6 6.1.48
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps 8.0.3
		colormatic: Colormatic 2.4.0+mc.1.18
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		completeconfig: CompleteConfig 1.3.3
		confabricate: confabricate 2.2.0-SNAPSHOT+4.1.1
		continuity: Continuity 1.0.3+1.18
		croptopia: Croptopia 1.7.4
		crowdin-translate: CrowdinTranslate 1.4+1.18
		cullleaves: Cull Leaves 2.3.2
		customportalapi: Custom Portal Api 0.0.1-beta47-1.18
		dark-loading-screen: Dark Loading Screen 1.6.11
		dcch: DCCH 1.0
		dehydration: Dehydration 1.2.5
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		dynamicfps: Dynamic FPS 2.0.6
		emerald_tools: Emerald Tools 1.3.33
		enhancedblockentities: Enhanced Block Entities 0.5+1.18
		entityculling: EntityCulling-Fabric 1.3.3
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd14
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9514
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9514
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabricloader: Fabric Loader 0.12.12
		fabrishot: Fabrishot 1.6.0
		fastopenlinksandfolders: FastOpenResourcePacks 1.0.0
		ferritecore: FerriteCore 4.0.0
		flamearrows: FlameArrows 1.18.1
		go-fish: Go Fish 1.4.1-1.18.1
		hologram-api: Hologram API 0.2.1+1.18-pre5
		indium: Indium 1.0.2-alpha1+mc1.18
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.1.3
		ironchests: Iron Chests for Fabric 1.5.3
		itemmodelfix: Item Model Fix 1.0.3+1.18
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.1.6
		lambdabettergrass: LambdaBetterGrass 1.2.1+1.17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		languagereload: Language Reload 1.2
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 5.0.0-beta.2+1.18-rc1
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.6
		midnightlib: MidnightLib 0.2.9
		minecraft: Minecraft 1.18.1
		mining_dims: Mining Dimensions 1.2.37
		mm: Manningham Mills 2.1
		moborigins: Mob Origins 1.8.0
		modmenu: Mod Menu 3.0.1
		more_gems: More Gems 1.3.53
		morechathistory: MoreChatHistory 1.1.0
		mostructures: Mo' Structures 1.3.0-pre1+1.18
		no-telemetry: No Telemetry 1.3.0
		nofade: No Fade 1.18-2.0.1
		nopearldamage: No Pearl Damage! 1.1.2
		notenoughcrashes: Not Enough Crashes 4.1.3+1.18
		omega-config: OmegaConfig 1.0.8
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		origins: Origins 1.3.1
		packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		paperdoll: PaperDoll 1.0.0-mc1.18-pre1
		placeholder-api: Placeholder API 1.1.3+1.17.1
		playerabilitylib: Pal 1.3.0
		polymer: Polymer 0.2.0-beta.12+1.18.1
		polymer-legacy: Polymer (Compatibility) 0.1.9+0.2.0-beta.12+1.18.1
		pride: Pride Lib 1.1.0+1.17
		pugh_tools: Pugh Tools 1.1.15
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reeses-sodium-options: Reese's Sodium Options 1.2.3
		repurposed_structures: Repurposed Structures 3.1.12+1.18.1
		roughlyenoughitems: Roughly Enough Items 7.1.356
		server_translations_api: Server Translations API 1.4.8+1.18-pre1
		sgui: sgui 1.0.0-rc6+1.18-pre5
		simple_backpack: SimpleBackpack 1.2.27
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.2
		smoothboot: Smooth Boot 1.18-1.7.0
		sodium: Sodium 0.4.0-alpha5+build.9
		sodium-extra: Sodium Extra 0.3.7
		spruceui: SpruceUI 3.3.0+1.17
		starlight: Starlight 1.0.0+fabric.d0a3220
		tooltipfix: ToolTip Fix 1.0.4-1.18
		universal-graves: Universal Graves 2.0.0-beta.1+1.18
		waystones: Waystones 2.4.0
		wi_zoom: WI Zoom 1.3-MC1.18.1
		xaerominimap: Xaero's Minimap 21.22.6
		yosbr: YOSBR 0.1.1
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 505 GL version 3.2.0 - Build 27.20.100.8681, Intel
	Window size: 1366x705
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 173538523) Generic error' x 2
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, lambdabettergrass/default (incompatible), continuity/default, continuity/glass_pane_culling_fix, file/Mod Menu Helper.zip
	Current Language: English (US)
	CPU: 4x Intel(R) Pentium(R) CPU N4200 @ 1.10GHz
	Client Crashes Since Restart: 2
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Not Enough Crashes (notenoughcrashes)
```

</details>

### Expected behavior

For the game to load.

### Observed/actual behavior

Says "saving world" for a few seconds before crashing.

### Steps To Reproduce

1. Launch FO
2. Try to open or create a world
3. Game crashes after saying "saving world"

### Modpack version

1.18.1

### Launcher

Minecraft Launcher (vanilla)

### Install method

Fresh install/new profile

### Additional context

[https://bytebin.lucko.me/y11SalU5hu](https://bytebin.lucko.me/y11SalU5hu)

**Comment by Madis0** [comment]
Thanks, collapsed your crash log and fixed the last URL.

I can see it's not quite a clean install, as you are using other mods with FO. My suggestions:

1. Dehydration caught my eye in the log, try disabling that
2. class_3324 is PlayerManager, so could be a mod that changes your player's abilities (similar to Dehydration)
3. Try disabling your other mods one by one

**Comment by 0963Iboss222** [comment]
Thanks! I disabled dehydration and I was able to open a world and play with no problem, i can finally play with 60 fps
