### ISSUE TITLE
Startup crash with Minihud

### ISSUE THREAD

**Issue by M1ChaeL756** [Fabulously-Optimized/fabulously-optimized#493]
### Describe the bug

when i open minecraft via the curseforge launcher, it doesn't do anything even tho the launcher dissapeard, when i tried to setup the log files when it starts in the settings theres a crash (below). I've added a few mods onto FO but it seemed to work fine, but when i tried to add minihud (like a smaller f3 you can toggle) it didn't work. I think the issue is caused by minihud, as described in the crash. But i really dont want to remove it! Is there any way it can work together with eachother?

### Modpack version

version 4.4.1

### Launcher

CurseForge Launcher

### Other things

- [X] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

### Additional context

heres the bug 

<details>

```

Mixin apply for mod minihud failed mixins.minihud.json:MixinScreen from mod minihud -> net.minecraft.class_408: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on onSendMessage could not find any targets matching 'Lnet/minecraft/class_408;method_44056(Ljava/lang/String;Z)V' in net.minecraft.class_408. Using refmap minihud-fabric-1.19-refmap.json [PREINJECT Applicator Phase -> mixins.minihud.json:MixinScreen from mod minihud -> Prepare Injections ->  -> handler$cbo000$onSendMessage(Ljava/lang/String;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on onSendMessage could not find any targets matching 'Lnet/minecraft/class_408;method_44056(Ljava/lang/String;Z)V' in net.minecraft.class_408. Using refmap minihud-fabric-1.19-refmap.json [PREINJECT Applicator Phase -> mixins.minihud.json:MixinScreen from mod minihud -> Prepare Injections ->  -> handler$cbo000$onSendMessage(Ljava/lang/String;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at jdk.internal.reflect.GeneratedConstructorAccessor62.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.client.main.Main.method_44604(Main.java:214)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
16:57:47.325
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_408 failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_408 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.client.main.Main.method_44604(Main.java:214)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 9 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.minihud.json:MixinScreen from mod minihud] from phase [DEFAULT] in config [mixins.minihud.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 12 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on onSendMessage could not find any targets matching 'Lnet/minecraft/class_408;method_44056(Ljava/lang/String;Z)V' in net.minecraft.class_408. Using refmap minihud-fabric-1.19-refmap.json [PREINJECT Applicator Phase -> mixins.minihud.json:MixinScreen from mod minihud -> Prepare Injections ->  -> handler$cbo000$onSendMessage(Ljava/lang/String;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at jdk.internal.reflect.GeneratedConstructorAccessor62.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 12 mor

```

</details>

**Comment by osfanbuff63** [comment]
Could you provide the `latest.log` from the directory that the CurseForge launcher uses for your minecraft folder? By default, you should be able to find it at `C:\Users\username\curseforge\minecraft\Instances\<instance_name>\logs` (I believe the default instance name is `Fabulously Optimized`, but don't know for sure.) assuming you are on Windows.

**Comment by M1ChaeL756** [comment]
[latest.log](https://github.com/Fabulously-Optimized/fabulously-optimized/files/9748078/latest.log)
it says this idk if it works when i attach a file it does this^

**Comment by osfanbuff63** [comment]
> [latest.log](https://github.com/Fabulously-Optimized/fabulously-optimized/files/9748078/latest.log) it says this idk if it works when i attach a file it does this^

It works, but apparently this log didn't have the crash in it, so just try readding MiniHUD and then send the log again if you can reproduce the crash.

**Comment by M1ChaeL756** [comment]
[latest.log](https://github.com/Fabulously-Optimized/fabulously-optimized/files/9748219/latest.log)

**Comment by M1ChaeL756** [comment]
this one is the crash i think

**Comment by M1ChaeL756** [comment]
[latest.log](https://github.com/Fabulously-Optimized/fabulously-optimized/files/9757013/latest.log)
this is the one with the crash i think

**Comment by M1ChaeL756** [comment]
oh oops i commented it again sorry!

**Comment by M1ChaeL756** [comment]
btw already a huge thank you for even looking at the bug!

**Comment by Madis0** [comment]
I can see that your MiniHud is 0.22.0, while the latest version is 0.23.3 - that is probably your issue.
