### ISSUE TITLE
Crash on startup on M1 Mac when using Java Zulu 17

### ISSUE THREAD

**Issue by Leonardo-Fiori** [Fabulously-Optimized/fabulously-optimized#515]
### Describe the bug

Game does not start, crashes in the launcher (MultiMC) when using Java Zulu 17 on Macos. Works with Java Tem 17, but performance is at least 3x worse due to the fact that Java Tem is not native for M1.

### Modpack version

4.4.6

### Launcher

MultiMC

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

### Additional context

```
[10:42:38] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Applications/MultiMC.app/Data/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[10:42:38] [main/INFO]: Compatibility level set to JAVA_16
[10:42:38] [main/INFO]: Compatibility level set to JAVA_17
[10:42:39] [main/INFO]: Preloading Debugify
[10:42:39] [main/INFO]: Loaded configuration file for Lithium: 105 options available, 1 override(s) found
[10:42:39] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 2 override(s) found
[10:42:39] [main/INFO]: Loaded configuration file for Sodium Extra: 27 options available, 0 override(s) found
[10:42:39] [main/WARN]: Force disabled MC-122477 because it only applies to OS: LINUX
[10:42:39] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[10:42:39] [main/WARN]: Force-disabling mixin 'features.fast_biome_colors.MixinBackgroundRenderer' as rule 'mixin.features.fast_biome_colors' (added by mods [colormatic]) disables it and children
[10:42:39] [main/WARN]: Force-disabling mixin 'features.fast_biome_colors.MixinClientWorld' as rule 'mixin.features.fast_biome_colors' (added by mods [colormatic]) disables it and children
[10:42:39] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[10:42:39] [main/INFO]: I used the json to destroy the json
[10:42:39] [main/INFO]: Smooth Boot config initialized
[10:42:39] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[10:42:40] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[10:42:40] [main/INFO]: Mixing server.MixinPlayer from nochatreports.mixins.json into net.minecraft.class_1657
[10:42:41] [main/INFO]: Building unoptimized datafixer
[10:42:42] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder from mod sodium, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[10:42:42] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[10:42:42] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[10:42:42] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[10:42:42] [Render thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[10:42:43] [Render thread/INFO]: Mixing client.MixinTitleScreen from nochatreports.mixins.json into net.minecraft.class_442
[10:42:43] [Render thread/INFO]: Mixing client.MixinLocalPlayer from nochatreports.mixins.json into net.minecraft.class_746
[10:42:43] [Render thread/INFO]: Mixing client.MixinChatScreen from nochatreports.mixins.json into net.minecraft.class_408
[10:42:43] [Render thread/INFO]: Renaming synthetic method lambda$onInit$4(Lnet/minecraft/class_4185;Lnet/minecraft/class_4587;II)V to md49b454$lambda$onInit$4$1 in nochatreports.mixins.json:client.MixinChatScreen from mod nochatreports
[10:42:43] [Render thread/INFO]: Renaming synthetic method lambda$onInit$3(Lnet/minecraft/class_4185;)V to md49b454$lambda$onInit$3$2 in nochatreports.mixins.json:client.MixinChatScreen from mod nochatreports
[10:42:43] [Render thread/INFO]: Renaming synthetic method lambda$onInit$2(Lcom/aizistral/nochatreports/core/ServerSafetyLevel;Lnet/minecraft/class_4185;Lnet/minecraft/class_4587;II)V to md49b454$lambda$onInit$2$3 in nochatreports.mixins.json:client.MixinChatScreen from mod nochatreports
[10:42:43] [Render thread/INFO]: Renaming synthetic method lambda$onInit$1(Lnet/minecraft/class_4185;)V to md49b454$lambda$onInit$1$4 in nochatreports.mixins.json:client.MixinChatScreen from mod nochatreports
[10:42:43] [Render thread/INFO]: Renaming synthetic method lambda$onBeforeMessage$0(Ljava/lang/String;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lcom/aizistral/nochatreports/encryption/Encryptor;)V to md49b454$lambda$onBeforeMessage$0$5 in nochatreports.mixins.json:client.MixinChatScreen from mod nochatreports
[10:42:43] [Render thread/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at net.minecraft.class_6396.method_37123(class_6396.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_37274(class_310.java:2359) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_22681(class_310.java:2354) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:214) ~[minecraft-1.19.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.10.jar:?]
	... 10 more
Process exited with code 1 (0x1).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
```

**Comment by Julienraptor01** [comment]
You did use a launcher that support aarch64 (arm64) and an aarch64 (arm64) bin of jre/jdk right ?

**Comment by Leonardo-Fiori** [comment]
My bad, was using zulu17 but forgot to complete the setup for arm. Now using Prism Launcher (essentially MultiMC but also for arm) and it's working
