### ISSUE TITLE
MemoryLeakFix

### ISSUE THREAD

**Issue by TheMangoNinja8** [Fabulously-Optimized/fabulously-optimized#516]
### Describe the bug

memoryleakfix-1.19-0.7.0 says it's incompatible with 1.19.2 
I've tried using both versions of the mod.

This is my first time making a bug report, Please let me know if you need any additional info.

### Modpack version

4.2.0

### Launcher

CurseForge Launcher

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [X] I added/removed some mods or resource packs (mention, which ones)

### Additional context

Additional Mods Added:
MaLiLib - masady
Litematica - masady
Better F3 - cominixo
Tweakaroo - masady
Mini HUD - masady
Free Cam - hashalites
Xaero's Minimap - xaero96
Inventory HUD+ - dmitrylovin
Boosted Brightness - aloivmada

Error Message:
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'memory Leak Fix' (memoryleakfix) 1.19-0.7.0 with any version that is compatible with:
		 - minecraft 1.19.2
Unmet dependency listing:
	 - Mod 'memory Leak Fix' (memoryleakfix) 1.19-0.7.0 requires version 1.19 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by TheMangoNinja8** [comment]
Thanks!
