### ISSUE TITLE
Crash when opening Bordeless Mining's config menu

### ISSUE THREAD

**Issue by Kiirx** [Fabulously-Optimized/fabulously-optimized#730]
### Describe the bug

Here's the error

```
[10:12:08] [Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.class_148: Ticking screen
	at net.minecraft.class_437.method_25412(class_437.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1925) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[1.20.2-0.14.22.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.class_342.method_1865()'
	at link.infra.borderlessmining.config.ConfigScreen$ConfigListTextField.tick(ConfigScreen.java:248) ~[borderless-mining-1.1.8+1.20.1.jar:?]
	at link.infra.borderlessmining.config.ConfigScreen$ConfigListWidget.tick(ConfigScreen.java:54) ~[borderless-mining-1.1.8+1.20.1.jar:?]
	at link.infra.borderlessmining.config.ConfigScreen.method_25393(ConfigScreen.java:117) ~[borderless-mining-1.1.8+1.20.1.jar:?]
	at net.minecraft.class_310.method_1572(class_310.java:1925) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[client-intermediary.jar:?]
	... 7 more
```

### Modpack version

5.4.0-alpha.1 1.20.2

### Launcher

ModRinth App (yeah ik it's not supported but it's not what matters)

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

**Comment by Madis0** [comment]
Alpha is prone to have such bugs, so that makes sense. However, I wonder: does the mod itself work for you, when you switch it on from config file and then launch the game?

**Comment by Kiirx** [comment]
> Alpha is prone to have such bugs, so that makes sense. However, I wonder: does the mod itself work for you, when you switch it on from config file and then launch the game?

Isn't it activated by default? I have no problem ingame but opening the config menu will still make me crash

**Comment by Madis0** [comment]
No, it is one of the few mods in FO that isn't activated by default, just there because there is a target audience who do enable it.

**Comment by Kiirx** [comment]
> No, it is one of the few mods in FO that isn't activated by default, just there because there is a target audience who do enable it.

oh ok so where do I activate it? everything is already ON on modrinth

**Comment by Madis0** [comment]
(Instance folder) -> config -> borderlessmining.json -> `"enableBorderlessFullscreen":true` -> launch the game -> set it to normal fullscreen (it should override it)

**Comment by Kiirx** [comment]
It does seem to work when I enable it from cfg file

**Comment by Madis0** [comment]
Alright, then I'll just disable the config button for a short while until the mod updates.

**Comment by Kiirx** [comment]
> Alright, then I'll just disable the config button for a short while until the mod updates.

Okay thanks should I keep the issue opened?

**Comment by Madis0** [comment]
Yes, I'll close it once resolved.
