### ISSUE TITLE
Unable to use resource packs that use colormaps

### ISSUE THREAD

**Issue by thrustmctrunkpunch** [Fabulously-Optimized/fabulously-optimized#868]
### Describe the bug

The game gets stuck loading when i have a resource pack in the folder (sapixcraft specifically). I can confirm the resource pack works in other versions of the modpack (1.20.4 specifically). It doesnt actually crash but it resets the loading bar once before never moving passed ~90%. Starts fine when the folder is empty

### Modpack version

1.20.6

### Launcher

CurseForge App

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

**Comment by TheBossMagnus** [comment]
right click on the modpack tile → Open Folder
Now send us the log file you have: latest.log

**Comment by jorden2895** [comment]
I got the same error when using "BetterVanillaBuilding"

**Comment by Madis0** [comment]
Your issue seems to be this: https://github.com/MehVahdJukaar/polytone/issues/55

**Comment by Tisawesomeness** [comment]
> I got the same error when using "BetterVanillaBuilding"

Open the pack and remove `assets/minecraft/optifine/colormap/color.properties` as a workaround or wait until BetterVanillaBuilding V3.5 for the fix.

**Comment by Madis0** [comment]
As of FO 9.0.0-beta.1 and [Sapixcraft 1.20 32x](https://www.curseforge.com/minecraft/texture-packs/sapixcraft/files/6259543), there is an informational toast, but the pack loads fine.

![Image](https://github.com/user-attachments/assets/96ac3343-35fa-41f7-834c-4658563bcfbb)

For reference, this is what the log says:

```
Polytone version: 1.21.5-3.4.0
[2025-05-12 18:33:27] Block modifiers Reloader failed to parse some resources. Check lines below to see where the error was:
java.lang.IllegalStateException: Could not find any colormap texture .png associated with path minecraft:sand for colormap 'Inlined Colormap from modifier minecraft:sand'
	at knot//net.mehvahdjukaar.polytone.colormap.ColormapsManager.tryAcceptingTexture(ColormapsManager.java:228)
	at knot//net.mehvahdjukaar.polytone.colormap.ColormapsManager.tryAcceptingTextureGroup(ColormapsManager.java:164)
	at knot//net.mehvahdjukaar.polytone.colormap.ColormapsManager.tryAcceptingTextureGroup(ColormapsManager.java:155)
	at knot//net.mehvahdjukaar.polytone.block.BlockPropertiesManager.parseWithLevel(BlockPropertiesManager.java:152)
	at knot//net.mehvahdjukaar.polytone.block.BlockPropertiesManager.parseWithLevel(BlockPropertiesManager.java:29)
	at knot//net.mehvahdjukaar.polytone.utils.CompoundReloader.processTyped(CompoundReloader.java:112)
	at knot//net.mehvahdjukaar.polytone.utils.CompoundReloader.applyWithLevel(CompoundReloader.java:65)
	at knot//net.mehvahdjukaar.polytone.Polytone.onTagsReceived(Polytone.java:124)
	at knot//net.mehvahdjukaar.polytone.fabric.PolytoneFabric.lambda$onInitializeClient$0(PolytoneFabric.java:34)
	at knot//net.fabricmc.fabric.api.event.lifecycle.v1.CommonLifecycleEvents.lambda$static$0(CommonLifecycleEvents.java:33)
	at knot//net.minecraft.class_8674.handler$bae000$fabric-lifecycle-events-v1$invokeTagsLoaded(class_8674.java:1034)
	at knot//net.minecraft.class_8674.method_57043(class_8674.java:117)
	at knot//net.minecraft.class_8674.method_57044(class_8674.java:109)
	at knot//net.minecraft.class_8674.method_52794(class_8674.java:117)
	at knot//net.minecraft.class_8733.method_53041(class_8733.java:22)
	at knot//net.minecraft.class_8733.method_65081(class_8733.java:8)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:27)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:164)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:138)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:123)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1308)
	at knot//net.minecraft.class_310.method_1514(class_310.java:936)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```
so that is up to the pack creator to fix, but the main issue here (loading problem) is fixed now.
