### ISSUE TITLE
Incompatible mods found!

### ISSUE THREAD

**Issue by FatheredPuma81** [Fabulously-Optimized/fabulously-optimized#902]
### Describe the bug

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'ResolutionControl+' (resolutioncontrol) 1.19.3-3.0.0 with any version that is compatible with:
		 - minecraft 1.21.1
More details:
	 - Mod 'ResolutionControl+' (resolutioncontrol) 1.19.3-3.0.0 requires version 1.19.3-rc.3 or version 1.19.3 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Modpack version

6.2.0

### Launcher

CurseForge App

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

**Comment by FatheredPuma81** [comment]
My bad it was an issue caused by Curseforge... again.
