### ISSUE TITLE
Game won't launch

### ISSUE THREAD

**Issue by Malerax** [Fabulously-Optimized/fabulously-optimized#904]
### Describe the bug

I have the standard modpack, but have added Essential modpack, and 2 map mods.
I updated the modpack yesterday, and now I can't launch the game... any ideas?

I am loading through ATLauncher

### Modpack version

6.4.0-Aplha.1

### Launcher

CurseForge App

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

### Additional context

[25/10/2024 14:23:56 pm] -- Initialization --
[25/10/2024 14:23:56 pm] Details:
[25/10/2024 14:23:56 pm] 	Modules: 
[25/10/2024 14:23:56 pm] 		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		CRYPT32.dll:Crypto API32:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		ColorAdapterClient.dll:Microsoft Color Adapter Client:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.19041.3930:Microsoft Corporation
[25/10/2024 14:23:56 pm] 		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.19041.3636:Microsoft Corporation
[25/10/2024 14:23:56 pm] 		DBGHELP.DLL:Windows Image Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		DEVOBJ.dll:Device Information Set DLL:10.0.19041.3996 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		DNSAPI.dll:DNS Client API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		GDI32.dll:GDI Client DLL:10.0.19041.3996 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		GLU32.dll:OpenGL Utility Library DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.3996 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		MSCTF.dll:MSCTF Server DLL:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		MpOav.dll:IOfficeAntiVirus Module:4.18.24080.9 (f49fb7de0d838aeebbdbd940314a35a90705840e):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		NLAapi.dll:Network Location Awareness 2:10.0.19041.4123 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		NSI.dll:NSI User-mode interface DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		OLEAUT32.dll:OLEAUT32.DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		Ole32.dll:Microsoft OLE for Windows:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		POWRPROF.dll:Power Profile Helper DLL:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		PROPSYS.dll:Microsoft Property System:7.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		PSAPI.DLL:Process Status Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		Pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		RPCRT4.dll:Remote Procedure Call Runtime:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		SETUPAPI.dll:Windows Setup API:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		SHCORE.dll:SHCORE:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 		USER32.dll:Multi-User Windows USER API Client DLL:10.0.19041.4522 (WinBuild.160101.0800):Microsoft Corporation
[25/10/2024 14:23:56 pm] 	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 1012135.25, total: 1907712.00
[25/10/2024 14:23:56 pm] 			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.59+c47b9d4340
[25/10/2024 14:23:56 pm] 			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.12+c47b9d4340
[25/10/2024 14:23:56 pm] 			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.0+c47b9d4340
[25/10/2024 14:23:56 pm] 		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.1+1.21.2-fabric
[25/10/2024 14:23:56 pm] #@!@# Game crashed! Crash report saved to: #@!@# **USERSDIR**\instances\FabulouslyOptimized\crash-reports\crash-2024-10-25_14.23.56-client.txt
[25/10/2024 14:23:56 pm] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
[25/10/2024 14:23:56 pm] If you're having issues, please visit the Discord server for the modpack at https://download.fo/discord
[25/10/2024 14:23:56 pm] Checking for updated files!
[25/10/2024 14:23:56 pm] Checking for updates to CurseForge instances
[25/10/2024 14:23:56 pm] Checking for updates to Modrinth instances
[25/10/2024 14:23:56 pm] com.atlauncher.network.DownloadException: https://api.modrinth.com/v2/project/3HVNJwgo/version request wasn't successful: Response{protocol=http/1.1, code=404, message=Not Found, url=https://api.modrinth.com/v2/project/3HVNJwgo/version}
[25/10/2024 14:23:56 pm] 	at com.atlauncher.network.Download.execute(Download.java:334)
[25/10/2024 14:23:56 pm] 	at com.atlauncher.network.Download.asTypeWithThrow(Download.java:179)
[25/10/2024 14:23:56 pm] 	at com.atlauncher.network.Download.asType(Download.java:186)
[25/10/2024 14:23:56 pm] 	at com.atlauncher.network.Download.asType(Download.java:200)
[25/10/2024 14:23:56 pm] 	at com.atlauncher.utils.ModrinthApi.getVersions(ModrinthApi.java:270)
[25/10/2024 14:23:56 pm] 	at com.atlauncher.utils.ModrinthApi.getVersions(ModrinthApi.java:220)
[25/10/2024 14:23:56 pm] 	at com.atlauncher.managers.ModrinthModpackUpdateManager.lambda$checkForUpdates$2(ModrinthModpackUpdateManager.java:92)
[25/10/2024 14:23:56 pm] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[25/10/2024 14:23:56 pm] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[25/10/2024 14:23:56 pm] 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
[25/10/2024 14:23:56 pm] 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[25/10/2024 14:23:56 pm] 	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
[25/10/2024 14:23:56 pm] 	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
[25/10/2024 14:23:56 pm] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[25/10/2024 14:23:56 pm] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
[25/10/2024 14:23:56 pm] 	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
[25/10/2024 14:23:56 pm] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[25/10/2024 14:23:56 pm] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[25/10/2024 14:23:56 pm] com.atlauncher.network.DownloadException: https://api.modrinth.com/v2/project/3HVNJwgo/version request wasn't successful: Response{protocol=http/1.1, code=404, message=Not Found, url=https://api.modrinth.com/v2/project/3HVNJwgo/version}
	at com.atlauncher.network.Download.execute(Download.java:334)
	at com.atlauncher.network.Download.asTypeWithThrow(Download.java:179)
	at com.atlauncher.network.Download.asType(Download.java:186)
	at com.atlauncher.network.Download.asType(Download.java:200)
	at com.atlauncher.utils.ModrinthApi.getVersions(ModrinthApi.java:270)
	at com.atlauncher.utils.ModrinthApi.getVersions(ModrinthApi.java:220)
	at com.atlauncher.managers.ModrinthModpackUpdateManager.lambda$checkForUpdates$2(ModrinthModpackUpdateManager.java:92)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[25/10/2024 14:24:12 pm] Copied Log to clipboard
[25/10/2024 14:24:15 pm] Log uploaded and link copied to clipboard: https://paste.atlauncher.com/view/0d1b0c51-8d7d-43b2-ad43-49ad76e2fb0d
[25/10/2024 14:26:03 pm] Copied Log to clipboard

**Comment by Madis0** [comment]
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on beforeCharTypedEvent could not find any targets matching 'Lnet/minecraft/class_309;method_1458(Lnet/minecraft/class_364;II)V' in net/minecraft/class_309. Using refmap jei-1.21.1-fabric-refmap.json 

Seems like JEI is not yet updated for 1.21.3, and I am not sure the other mods you've added are either.
