### ISSUE TITLE
Pack doesnt start

### ISSUE THREAD

**Issue by Bartek200219** [Fabulously-Optimized/fabulously-optimized#906]
### Describe the bug

Pack downloaded from Modrinth using MultiMC doesn't start. Tried different java versions still the same issue.

### Modpack version

6.2.1

### Launcher

MultiMC

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

### Additional context

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium' at 'me.jellysquid.mods.sodium.client.SodiumPreLaunch'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium' at 'me.jellysquid.mods.sodium.client.SodiumPreLaunch'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 8 more
Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll
	at knot//org.lwjgl.system.Library.loadSystem(Library.java:174)
	at knot//org.lwjgl.system.Library.loadSystem(Library.java:64)
	at knot//org.lwjgl.system.Library.<clinit>(Library.java:52)
	at knot//org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
	at knot//org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:67)
	at knot//org.lwjgl.system.APIUtil.apiCreateLibrary(APIUtil.java:126)
	at knot//me.jellysquid.mods.sodium.client.platform.windows.api.Gdi32.<clinit>(Gdi32.java:12)
	at knot//me.jellysquid.mods.sodium.client.platform.windows.api.d3dkmt.D3DKMT.<clinit>(D3DKMT.java:28)
	at knot//me.jellysquid.mods.sodium.client.compatibility.environment.probe.GraphicsAdapterProbe.findAdapters$Windows(GraphicsAdapterProbe.java:56)
	at knot//me.jellysquid.mods.sodium.client.compatibility.environment.probe.GraphicsAdapterProbe.findAdapters(GraphicsAdapterProbe.java:29)
	at knot//me.jellysquid.mods.sodium.client.SodiumPreLaunch.onPreLaunch(SodiumPreLaunch.java:12)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 9 more

**Comment by Madis0** [comment]
> Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll

Launcher bug, you are probably unable to launch vanilla 1.21.1 either. Please ask MultiMC support about this.
